---
title: Cell cluster annotation and signature scoring
author: Florian Uhlitz
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    code_folding: hide
params: 
  seu_obj: ["_data/_patients/computed/anchored/seu_abc_epi_p007n_epi_p007t.rds"]
  cluster_res: 0.8
  nbin: 24
  grouping_var: ["sample_origin"]
---


```{r chunk000}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = F, warning = F, message = F)

```

```{r chunk010}

library(CMSclassifier)
library(magrittr)
library(tidyverse)
library(readxl)
library(stringr)
library(Seurat)
library(future)
plan(strategy = "multicore", workers = 32)
library(parallel)
library(progeny)
library(cowplot)
library(viridis)
library(knitr)
reticulate::use_condaenv("base")
theme_set(theme_cowplot())
seu_obj_file <- c("_data/computed/anchored/seu_merge_epi_p007n_strict_epi_p007t_strict.rds")
cluster_res <- 0.8
nbin <- 24
grouping_var <- "sample_origin"
seu_obj_file <- params$seu_obj
cluster_res <- params$cluster_res
nbin <- params$nbin
grouping_var <- params$grouping_var

```

# `r basename(seu_obj_file)`

```{r chunk020, fig.height=10, fig.width=10}

## Data loading 
seu_obj <- read_rds(seu_obj_file)

```

## Signature scoring 

```{r}

## signature annotation ---------------------------------------

## broad hallmark pathways
broad_pws <- read_lines("_data/signatures/h.all.v6.2.symbols.gmt") %>% 
  lapply(str_split, "\\t") %>% 
  unlist(recursive = F) %>% 
  lapply(function(x) setNames(list(x[-c(1:2)]), x[1])) %>% 
  unlist(recursive = F)

## morkel signatures
signature_list <- read_excel("_data/signatures/Signatures_Single_cells.xlsx") %>%
  lapply(function (x) {
    x[2:length(x)] %>%
      .[!is.na(.)] %>%
      toupper
  })

ERK_Targets <- read_tsv("_data/signatures/ILG_paper_table_EV1.tsv") %$%
  SYMBOL

ISC_LGR5 <- read_excel("_data/signatures/Munoz.xls", 12, skip = 2) %>%
  arrange(desc(`Overlap Group...11`)) %>% 
  select(`Official Gene Symbol`, `Overlap Group...11`) %>% 
  filter(`Overlap Group...11` > 2) %$%
  `Official Gene Symbol` %>%
  toupper

ISC.markers <- read_excel("_data/signatures/Munoz.xls", 12, skip = 2) %$%
  `Official Gene Symbol` %>%
  toupper

huCRC_IF <- read_excel("_data/signatures/invasive_front.xlsx", na = "n.s.", 
                       col_types = c("text", "numeric", "numeric", "numeric")) %>% 
  filter(log2fc_IF_T > 1, log2fc_IF_N > 1) %$% 
  Gene

merlos_suarez_markers <- read_excel("_data/signatures/merlos-suarez-ISC.xls", skip = 3) %>% 
  select(1:4) %>% 
  mutate_all(.funs = list(~str_remove_all(., "\\*"))) %>% 
  as.list %>% 
  lapply(function(x) x[!is.na(x)])

YAP_EGFR_UP <- read_excel("_data/signatures/YAP_EGFR.xlsx") %>% 
  select(Gene_Symbol, Fold_log2) %>% 
  filter(Fold_log2 > 3) %$%
  toupper(Gene_Symbol)

YAP_EGFR_DN <- read_excel("_data/signatures/YAP_EGFR.xlsx") %>% 
  select(Gene_Symbol, Fold_log2) %>% 
  filter(Fold_log2 < -3) %$%
  toupper(Gene_Symbol)

SSC2a <- read_excel("_data/signatures/SSC2_markers.xlsx", sheet = 1, skip = 3) %$%
  toupper(gene)
SSC2b <- read_excel("_data/signatures/SSC2_markers.xlsx", sheet = 2, skip = 3) %$%
  toupper(gene)
SSC2c <- read_excel("_data/signatures/SSC2_markers.xlsx", sheet = 3, skip = 3) %$%
  toupper(gene)

signature_list$`ERK targets` <- ERK_Targets
signature_list$ISC.markers <- ISC.markers
signature_list$ISC_LGR5 <- ISC_LGR5
signature_list$huCRC_IF <- huCRC_IF
signature_list <- append(signature_list, merlos_suarez_markers)
signature_list$YAP_EGFR_UP <- YAP_EGFR_UP
signature_list$YAP_EGFR_DN <- YAP_EGFR_DN
signature_list$SSC2a <- SSC2a
signature_list$SSC2b <- SSC2b
signature_list$SSC2c <- SSC2c

names(signature_list) <- make.names(names(signature_list))

## other signatures 
SMAD_targets <- read_lines("_data/signatures/SMAD.gmt") %>% 
  lapply(str_split, "\t") %>% 
  unlist(recursive = F) %>% 
  lapply(function(x) {
    l <- list()
    l[[x[1]]] <- x[-c(1:2)]
    return(l)}) %>% 
  unlist(recursive = F)

p38_targets <- read_lines("_data/signatures/p38.txt", skip = 2) %>% 
  str_remove_all("\t")

YAP_targets <- read_lines("_data/signatures/YAP_targets.txt", skip = 2)
YAP_targets_UP <- read_lines("_data/signatures/YAP_targets_UP.txt", skip = 2)
YAP_targets_DN <- read_lines("_data/signatures/YAP_targets_DN.txt", skip = 2)

CTNNB1_UP <- read_lines("_data/signatures/CTNNB1_UP.txt", skip = 2)
CTNNB1_DN <- read_lines("_data/signatures/CTNNB1_DN.txt", skip = 2)
nfkb_tian <- read_lines("_data/signatures/nfkb_tian.txt", skip = 2)
nfkb_wang <- read_lines("_data/signatures/nfkb_wang.txt", skip = 2)

yap_wang <- read_lines("_data/signatures/yap_wang.txt")

regev_markers <- read_excel("_data/signatures/regev-nature24489-s5.xlsx", skip = 5) %>%
  set_colnames(c("Goblet.regev", "Paneth.regev", "Tuft.regev",
                 "Enteroendocrine.regev", "Enteroprox.regev",
                 "Enterodist.regev")) %>% 
  mutate_all(.funs = function(x) toupper(x)) %>% 
  select(-Paneth.regev) %>% 
  as.list %>% 
  lapply(function(x) x[!is.na(x)])
regev_markers$Enterocyte.regev <- unique(c(regev_markers$Enterodist.regev, regev_markers$Enteroprox.regev))

cell_type_markers <- list(
  ISC.markers, regev_markers, signature_list$TA.cell.markers, 
  signature_list$Enterocyte.markers, signature_list$Paneth.cell.markers
) %>% 
  unlist %>% sort %>% unique


annotate_seu_obj <- function(seu_obj, nb = nbin) {
  
  ## CRC CMS subtype
  entrez_ids <- AnnotationDbi::select(org.Hs.eg.db::org.Hs.eg.db,
                                      keys = rownames(seu_obj@assays$SCT@data),
                                      columns = c("SYMBOL", "ENTREZID"),
                                      keytype = "SYMBOL") %>%
    distinct(SYMBOL, .keep_all = T)
  
  entrez_counts <- seu_obj@assays$SCT@data %>%
    as.matrix %>%
    set_rownames(entrez_ids$ENTREZID) %>%
    .[!is.na(rownames(.)),] %>% 
    as.data.frame
  
  ## Progeny pathways
  pathway_scores <- seu_obj@assays$SCT@data %>% 
    as.matrix %>% 
    progeny %>% 
    set_colnames(paste0(colnames(.), ".pathway")) %>% 
    as_tibble(rownames = "cell_id")
  
  seu_obj@meta.data <- seu_obj@meta.data %>%
    left_join(pathway_scores, by = "cell_id") %>%
    as.data.frame %>%
    set_rownames(.$cell_id)
  
  rp_genes <- rownames(seu_obj) %>%
    grep("^RPL|^RPS", ., value = T) %>% 
    unique
  
  hsp_genes <- rownames(seu_obj) %>% 
    grep("^HSP[9,A,B,D,E,H]|^DNAJ", ., value = T) %>% 
    sort
  
  yap_wang_sub <- yap_wang[yap_wang %in% rownames(seu_obj)]
  
  print(unique(seu_obj$sample_id))
  
  for (i in 1:length(broad_pws)) {
    seu_obj <- AddModuleScore(seu_obj, broad_pws[i], name = names(broad_pws)[i], nbin = nb, assay = "SCT")
  } 
  
  print("broad done")
  
  for (i in 1:length(signature_list)) {
    seu_obj <- AddModuleScore(seu_obj, signature_list[i], name = names(signature_list)[i], nbin = nb, assay = "SCT")
  }
  
  print("morkel done")
  
  for (i in 1:length(SMAD_targets)) {
    seu_obj <- AddModuleScore(seu_obj, SMAD_targets[i], name = names(SMAD_targets)[i], nbin = nb, assay = "SCT")
  }
  
  print("SMAD done")
  
  seu_obj <- AddModuleScore(seu_obj, list(p38_targets), name = "p38.targets", nbin = nb, assay = "SCT")
  
  seu_obj <- AddModuleScore(seu_obj, list(nfkb_tian), name = "NFkB.targets.tian", nbin = nb, assay = "SCT")
  seu_obj <- AddModuleScore(seu_obj, list(nfkb_wang), name = "NFkB.targets.wang", nbin = nb, assay = "SCT")
  
  print("TNFa done")
  
  seu_obj <- AddModuleScore(seu_obj, list(CTNNB1_UP), name = "CTNNB1.targets_UP", nbin = nb, assay = "SCT")
  seu_obj <- AddModuleScore(seu_obj, list(CTNNB1_DN), name = "CTNNB1.targets_DN", nbin = nb, assay = "SCT")
  
  print("Wnt done")
  
  seu_obj <- AddModuleScore(seu_obj, list(YAP_targets), name = "YAP.targets", nbin = nb, assay = "SCT")
  seu_obj <- AddModuleScore(seu_obj, list(YAP_targets_UP), name = "YAP.targets_UP", nbin = nb, assay = "SCT")
  seu_obj <- AddModuleScore(seu_obj, list(YAP_targets_DN), name = "YAP.targets_DN", nbin = nb, assay = "SCT")
  seu_obj <- AddModuleScore(seu_obj, list(yap_wang_sub), name = "YAP.Wang", nbin = nb, assay = "SCT")
  
  print("YAP done")
  
  for (i in 1:length(regev_markers)) {
    seu_obj <- AddModuleScore(seu_obj, regev_markers[i], name = names(regev_markers)[i], nbin = nb, assay = "SCT")
  }
  
  print("regev done")
  
  seu_obj <- AddModuleScore(seu_obj, list(hsp_genes), name = "HSP.score", nbin = nb, assay = "SCT")
  
  return(seu_obj)
  
}


add_cms <- function(seu_obj) {
  ## CRC CMS subtype
  entrez_ids <- AnnotationDbi::select(org.Hs.eg.db::org.Hs.eg.db,
                                      keys = rownames(seu_obj@assays$SCT@data),
                                      columns = c("SYMBOL", "ENTREZID"),
                                      keytype = "SYMBOL") %>%
    distinct(SYMBOL, .keep_all = T)

  entrez_counts <- seu_obj@assays$SCT@data %>%
    as.matrix %>%
    set_rownames(entrez_ids$ENTREZID) %>%
    .[!is.na(rownames(.)),] %>%
    as.data.frame

  #cell_bins <- cut(1:ncol(entrez_counts), parallel::detectCores()) %>%
  #  enframe %>%
  #  mutate(value = as.numeric(value)) %>%
  #  group_by(value) %>%
  #  summarise(name  = list(name)) %$%
  #  as.list(name)

  #cms_tbl1 <- parallel::mclapply(cell_bins, function(x) CMScaller(entrez_counts[,x], RNAseq = F, doPlot = F)) %>%
  #  lapply(as_tibble, rownames = "cell_id") %>%
  #  bind_rows %>%
  #  dplyr::rename(CMScaller = prediction,
  #                CMSc.p.value = p.value,
  #                CMSc.FDR = FDR)

  cms_tbl2 <- classifyCMS(entrez_counts) %$%
    RF.details %>%
    as_tibble(rownames = "cell_id")

  seu_obj@meta.data <- seu_obj@meta.data %>%
    #left_join(cms_tbl1, by = "cell_id") %>%
    left_join(cms_tbl2, by = "cell_id") %>%
    as.data.frame %>%
    set_rownames(.$cell_id)

  return(seu_obj)

}

seu_obj <- annotate_seu_obj(seu_obj)
seu_obj <- add_cms(seu_obj)
                                 
```

## Louvain clusters

```{r chunk030}

cluster_feature <- paste0(DefaultAssay(seu_obj), "_snn_res.", cluster_res)

seu_obj <- AddMetaData(seu_obj, metadata = FetchData(seu_obj, cluster_feature) %>% 
  as_tibble(rownames = "cell_id") %>% 
  deframe, col.name = "snn_cluster")

Idents(seu_obj) <- seu_obj$snn_cluster

```

```{r chunk035, fig.height=10, fig.width=15}

DimPlot(seu_obj, split.by = "sample_id", pt.size = 0.1, label = T, ncol = round(sqrt(length(unique(seu_obj$sample_id))+1))) + coord_fixed() + NoAxes()

```

## Cluster marker genes

```{r chunk040}

error_handling <- function(x) {
  if (!is.data.frame(x)) x <- set_rownames(data.frame(p_val = NA), "no_sig_genes")
  return(x)
}

snn_markers <- parallel::mclapply(unique(seu_obj$snn_cluster), function(x) FindMarkers(seu_obj, ident.1 = x, only.pos = T, logfc.threshold = 0.25, features = unique(c(rownames(seu_obj@assays$SCT@scale.data), VariableFeatures(seu_obj)))), mc.cores = parallel::detectCores()) %>% 
  lapply(error_handling) %>% 
  lapply(as_tibble, rownames = "gene") %>% 
  setNames(unique(seu_obj$snn_cluster)) %>% 
  bind_rows(.id = "cluster")

spread_markers <- . %>% 
  group_by(cluster) %>% 
  slice(1:100) %>% 
  mutate(rank = row_number(p_val_adj)) %>%
  distinct(cluster, gene, rank) %>% 
  na.omit() %>%
  spread(cluster, gene, fill = "")
  
kable(spread_markers(snn_markers))  

```

```{r chunk050}

HCA_epi <- read_excel("_data/signatures/regev-colon-mmc2.xlsx", sheet = 1)
HCA_str <- read_excel("_data/signatures/regev-colon-mmc2.xlsx", sheet = 2)
HCA_imm <- read_excel("_data/signatures/regev-colon-mmc2.xlsx", sheet = 3)

cell_type_names <- c(
  `Inflammatory Monocytes` = "Monocytes",
  T.CD4 = "CD4+ T",
  T.CD8 = "CD8+ T",
  M.Mast = "Mast",
  GC = "GCs",
  `B` = "B cells",
  F.Crypt = "Crypt FBs",
  F.Villus = "Villus FBs",
  `Post-capillary Venules` = "PC venules",
  `Inflammatory Fibroblasts` = "Infl. FBs",
  Myofibroblasts = "Myofib.",
  `Immature Enterocytes 1` = "Imma. Ent. 1",
  `Immature Enterocytes 2` = "Imma. Ent. 2",  
  `Immature Goblet` = "Imma. Gob.",
  Enteroendocrine = "EEC",
  `Enterocyte Progenitors` = "Ent. Prog.",
  `TA 2` = "Abs. TA",
  `TA 1` = "Abs. TA",
  `Secretory TA` = "Sec. TA"
)

HCA_marker <- bind_rows(HCA_epi, HCA_str, HCA_imm) %>% 
  mutate(ident = ifelse(ident %in% names(cell_type_names), cell_type_names[ident], ident))

HCA_meta <- read_excel("_data/signatures/regev-colon-mmc2.xlsx", sheet = 6)

get_sets <- function(superset) {
  filter(HCA_meta, Name == superset)$`Cell subsets` %>% 
    str_split(", ") %>% 
    unlist %>% 
    ifelse(. %in% names(cell_type_names), cell_type_names[.], .)
}

top_sets <- c("E.Epithelial", "F.Stromal", "I.Immune")
epi_sets <- unique(get_sets("E.Epithelial"))
epi_sets <- unique(epi_sets[!(epi_sets %in% c("Best4+ Enterocytes", "Imma. Ent. 1", "Imma. Ent. 2", "Cycling TA"))])
str_sets <- c("Crypt FBs", "Villus FBs", 
              "Infl. FBs", "Myofib.", "Microvascular", 
              "PC venules", "Endothelial", "Pericytes", "Glia")
imm_sets <- c("Macrophages", "DC1", "DC2", "Monocytes", "Mast", "NKs", "ILCs", 
              "CD4+ T", "CD8+ T", "Plasma", "Follicular", "GCs", "B cells")

get_marker_mat <- function(sets, min.alpha = 0, n.slice = 20) {
  HCA_marker %>% 
    filter(ident %in% sets) %>% 
    filter(alpha > min.alpha) %>% 
    # mutate(ident = str_remove_all(ident, "E\\.|\\F.|I\\.")) %>% 
    select(ident, gene) %>% 
    group_by(ident) %>% 
    slice(1:n.slice) %>% 
    ungroup %>% 
    mutate(expression = 1) %>% 
    spread(ident, expression, fill = 0) %>% 
    as.data.frame %>% 
    set_rownames(.$gene) %>% 
    .[,-1] %>% 
    as.matrix # %>% 
    #.[apply(.,1,sum)<=3,]
}

marker_mat_top <- get_marker_mat(top_sets, 0.5, 20)
marker_mat_epi <- get_marker_mat(epi_sets, 0.25, 20)
marker_mat_str <- get_marker_mat(str_sets, 0.25, 20)
marker_mat_imm <- get_marker_mat(imm_sets, 0.25, 20)
marker_mat_all <- get_marker_mat(c(epi_sets, str_sets, imm_sets), 0.25, 20)

```

```{r chunk060, fig.height=12, fig.width=10}

annotate_cell_type <- function(seu_obj, marker_mat, type_name) {
  
  test_set <- snn_markers %>%
    filter(p_val_adj < 0.01) %>%
    rename(snn_cluster = cluster) %>%
    group_by(snn_cluster) %>% 
    slice(1:100) %>%
    mutate(k = length(snn_cluster)) %>%
    ungroup %>%
    select(snn_cluster, gene, k) %>% 
    mutate(join_helper = 1) %>% 
    group_by(snn_cluster, join_helper, k) %>%
    nest(gene) %>% 
    rename(test_set = data)

  ref_set <- marker_mat %>% 
    as.data.frame %>% 
    as_tibble(rownames = "gene") %>% 
    gather(cell_type, value, -gene) %>% 
    filter(value == 1) %>% 
    group_by(cell_type) %>% 
    filter(gene %in% rownames(seu_obj)) %>% 
    mutate(m = length(gene),
           n = length(rownames(seu_obj))-m,
           join_helper = 1) %>% 
    group_by(cell_type, m, n, join_helper) %>%
    nest(gene) %>% 
    rename(ref_set = data)

  hyper_tbl <- test_set %>% 
    left_join(ref_set, by = "join_helper") %>% 
    group_by(snn_cluster, cell_type, m, n, k) %>%
    do(q = length(intersect(unlist(.$ref_set), unlist(.$test_set)))) %>%
    mutate(pval = 1-phyper(q = q, m = m, n = n, k = k)) %>%
    ungroup %>%
    mutate(qval = p.adjust(pval, "BH"),
           sig = qval < 0.05)

  cell_anno_tbl <- hyper_tbl %>% 
    arrange(qval) %>%
    group_by(snn_cluster) %>% 
    slice(1) %>% 
    filter(sig) %>%
    select(snn_cluster, cell_type) %>% 
    set_colnames(c("snn_cluster", type_name))
  
  seu_obj@meta.data <- seu_obj@meta.data %>% 
    as.data.frame() %>% 
    left_join(cell_anno_tbl, by = "snn_cluster") %>% 
    as.data.frame() %>% 
    set_rownames(.$cell_id)

  return(seu_obj)

}
                                  
#seu_obj$cell_type_epi <- NULL  
#seu_obj$cell_type_imm <- NULL  
#seu_obj$cell_type_str <- NULL 
seu_obj <- annotate_cell_type(seu_obj, marker_mat_epi, "cell_type_epi")
seu_obj <- annotate_cell_type(seu_obj, marker_mat_imm, "cell_type_imm")
seu_obj <- annotate_cell_type(seu_obj, marker_mat_str, "cell_type_str")



```

```{r chunk080, fig.height=10,fig.width=15}


if (str_detect(seu_obj_file, "epi_")) {
  DimPlot(seu_obj, group.by = "cell_type_epi", pt.size = 0.1, label = T, 
          ncol = round(sqrt(length(unique(seu_obj$sample_id))+1))) + coord_fixed() + NoAxes()
}
if (str_detect(seu_obj_file, "imm_")) {
  DimPlot(seu_obj, group.by = "cell_type_imm", pt.size = 0.1, label = T, 
          ncol = round(sqrt(length(unique(seu_obj$sample_id))+1))) + coord_fixed() + NoAxes()
}
if (str_detect(seu_obj_file, "str_")) {
  DimPlot(seu_obj, group.by = "cell_type_str", pt.size = 0.1, label = T, 
          ncol = round(sqrt(length(unique(seu_obj$sample_id))+1))) + coord_fixed() + NoAxes()
}


```

```{r chunk100}

write_rds(seu_obj, paste0("_data/computed/annotated/", basename(seu_obj_file)))
write_rds(snn_markers, paste0("_data/computed/annotated/", basename(seu_obj_file), "_markers.rds"))

```

