---
title: Seurat merging and anchoring
author: Florian Uhlitz
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    code_folding: hide
params: 
  seu_obj: [NULL]
  max_cells: 2000
---


```{r chunk000}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = F, warning = F, message = F)

```

```{r chunk010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(stringr)
reticulate::use_condaenv("base")

```

## subset data

```{r chunk020}

# ## debugging example pars
# seu_obj_file <- "_data/computed/raw/seu_raw_epi_p009n1.rds"
# max_cells <- 2000
# seu_obj_file <- params$seu_obj
# max_cells <- params$max_cells

sample_seu <- function(seu_obj, seed = 42, nmax = max_cells) {
  set.seed(seed)
  if (length(colnames(seu_obj)) > nmax) seu_obj <- subset(seu_obj, cells = sample(colnames(seu_obj), nmax))
  return(seu_obj)
}

seu_obj <- sample_seu(read_rds(seu_obj_file))
write_rds(seu_obj, str_replace_all(seu_obj_file, "seu_raw", "seu_sub"))

```
